# Generated by Django 5.1.2 on 2024-12-04 19:46

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestor_archivos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentAsociadosDiagramasFlujo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentFormatosAsociados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('codigo', models.CharField(max_length=100)),
                ('caracterizacion', models.CharField(max_length=100)),
                ('procedimiento', models.CharField(max_length=100)),
                ('file', models.FileField(max_length=200, upload_to='lib/', verbose_name='Archivo')),
                ('fecha_creacion', models.DateTimeField(default=datetime.datetime(2024, 12, 4, 14, 46, 56))),
            ],
        ),
        migrations.CreateModel(
            name='DocumentImage_admisiones_registro_control',
            fields=[
                ('documentasociadosdiagramasflujo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='documentacion.documentasociadosdiagramasflujo')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DocumentImage_admisiones_registro_control', to='gestor_archivos.document_admisiones_registro_control')),
            ],
            options={
                'db_table': 'DocumentImage_admisiones_registro_control',
            },
            bases=('documentacion.documentasociadosdiagramasflujo',),
        ),
        migrations.CreateModel(
            name='DocumentImage_aseguramiento_calidad_academica',
            fields=[
                ('documentasociadosdiagramasflujo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='documentacion.documentasociadosdiagramasflujo')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DocumentImage_aseguramiento_calidad_academica', to='gestor_archivos.document_aseguramiento_calidad_academica')),
            ],
            options={
                'db_table': 'DocumentImage_aseguramiento_calidad_academica',
            },
            bases=('documentacion.documentasociadosdiagramasflujo',),
        ),
        migrations.CreateModel(
            name='DocumentImage_aseguramiento_calidad_procesos',
            fields=[
                ('documentasociadosdiagramasflujo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='documentacion.documentasociadosdiagramasflujo')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DocumentImage_aseguramiento_calidad_procesos', to='gestor_archivos.document_aseguramiento_calidad_procesos')),
            ],
            options={
                'db_table': 'DocumentImage_aseguramiento_calidad_procesos',
            },
            bases=('documentacion.documentasociadosdiagramasflujo',),
        ),
        migrations.CreateModel(
            name='DocumentImage_auditorias',
            fields=[
                ('documentasociadosdiagramasflujo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='documentacion.documentasociadosdiagramasflujo')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DocumentImage_auditorias', to='gestor_archivos.document_auditorias')),
            ],
            options={
                'db_table': 'DocumentImage_auditorias',
            },
            bases=('documentacion.documentasociadosdiagramasflujo',),
        ),
        migrations.CreateModel(
            name='DocumentImage_bienestar_institucional',
            fields=[
                ('documentasociadosdiagramasflujo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='documentacion.documentasociadosdiagramasflujo')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DocumentImage_bienestar_institucional', to='gestor_archivos.document_bienestar_institucional')),
            ],
            options={
                'db_table': 'DocumentImage_bienestar_institucional',
            },
            bases=('documentacion.documentasociadosdiagramasflujo',),
        ),
        migrations.CreateModel(
            name='DocumentImage_comunicacion',
            fields=[
                ('documentasociadosdiagramasflujo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='documentacion.documentasociadosdiagramasflujo')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DocumentImage_comunicacion', to='gestor_archivos.document_comunicacion')),
            ],
            options={
                'db_table': 'DocumentImage_comunicacion',
            },
            bases=('documentacion.documentasociadosdiagramasflujo',),
        ),
        migrations.CreateModel(
            name='DocumentImage_control_disciplinario',
            fields=[
                ('documentasociadosdiagramasflujo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='documentacion.documentasociadosdiagramasflujo')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DocumentImage_control_disciplinario', to='gestor_archivos.document_control_disciplinario')),
            ],
            options={
                'db_table': 'DocumentImage_control_disciplinario',
            },
            bases=('documentacion.documentasociadosdiagramasflujo',),
        ),
        migrations.CreateModel(
            name='DocumentImage_desarrollo_curricular',
            fields=[
                ('documentasociadosdiagramasflujo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='documentacion.documentasociadosdiagramasflujo')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DocumentImage_desarrollo_curricular', to='gestor_archivos.document_desarrollo_curricular')),
            ],
            options={
                'db_table': 'DocumentImage_desarrollo_curricular',
            },
            bases=('documentacion.documentasociadosdiagramasflujo',),
        ),
        migrations.CreateModel(
            name='DocumentImage_enseñanza_prendizaje_evaluacion',
            fields=[
                ('documentasociadosdiagramasflujo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='documentacion.documentasociadosdiagramasflujo')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DocumentImage_enseñanza_prendizaje_evaluacion', to='gestor_archivos.document_enseñanza_prendizaje_evaluacion')),
            ],
            options={
                'db_table': 'DocumentImage_enseñanza_prendizaje_evaluacion',
            },
            bases=('documentacion.documentasociadosdiagramasflujo',),
        ),
        migrations.CreateModel(
            name='DocumentImage_extension_proyeccion',
            fields=[
                ('documentasociadosdiagramasflujo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='documentacion.documentasociadosdiagramasflujo')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DocumentImage_extension_proyeccion', to='gestor_archivos.document_extension_proyeccion')),
            ],
            options={
                'db_table': 'DocumentImage_extension_proyeccion',
            },
            bases=('documentacion.documentasociadosdiagramasflujo',),
        ),
        migrations.CreateModel(
            name='DocumentImage_gestion_contractual',
            fields=[
                ('documentasociadosdiagramasflujo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='documentacion.documentasociadosdiagramasflujo')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DocumentImage_gestion_contractual', to='gestor_archivos.document_gestion_contractual')),
            ],
            options={
                'db_table': 'DocumentImage_gestion_contractual',
            },
            bases=('documentacion.documentasociadosdiagramasflujo',),
        ),
        migrations.CreateModel(
            name='DocumentImage_gestion_desarrollo_humano',
            fields=[
                ('documentasociadosdiagramasflujo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='documentacion.documentasociadosdiagramasflujo')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DocumentImage_gestion_desarrollo_humano', to='gestor_archivos.document_gestion_desarrollo_humano')),
            ],
            options={
                'db_table': 'DocumentImage_gestion_desarrollo_humano',
            },
            bases=('documentacion.documentasociadosdiagramasflujo',),
        ),
        migrations.CreateModel(
            name='DocumentImage_gestion_documental',
            fields=[
                ('documentasociadosdiagramasflujo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='documentacion.documentasociadosdiagramasflujo')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DocumentImage_gestion_documental', to='gestor_archivos.document_gestion_documental')),
            ],
            options={
                'db_table': 'DocumentImage_gestion_documental',
            },
            bases=('documentacion.documentasociadosdiagramasflujo',),
        ),
        migrations.CreateModel(
            name='DocumentImage_gestion_informacion',
            fields=[
                ('documentasociadosdiagramasflujo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='documentacion.documentasociadosdiagramasflujo')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DocumentImage_gestion_informacion', to='gestor_archivos.document_gestion_informacion')),
            ],
            options={
                'db_table': 'DocumentImage_gestion_informacion',
            },
            bases=('documentacion.documentasociadosdiagramasflujo',),
        ),
        migrations.CreateModel(
            name='DocumentImage_gestion_investigacion',
            fields=[
                ('documentasociadosdiagramasflujo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='documentacion.documentasociadosdiagramasflujo')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DocumentImage_gestion_investigacion', to='gestor_archivos.document_gestion_investigacion')),
            ],
            options={
                'db_table': 'DocumentImage_gestion_investigacion',
            },
            bases=('documentacion.documentasociadosdiagramasflujo',),
        ),
        migrations.CreateModel(
            name='DocumentImage_gestion_juridica',
            fields=[
                ('documentasociadosdiagramasflujo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='documentacion.documentasociadosdiagramasflujo')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DocumentImage_gestion_juridica', to='gestor_archivos.document_gestion_juridica')),
            ],
            options={
                'db_table': 'DocumentImage_gestion_juridica',
            },
            bases=('documentacion.documentasociadosdiagramasflujo',),
        ),
        migrations.CreateModel(
            name='DocumentImage_gestion_recursos_financieros',
            fields=[
                ('documentasociadosdiagramasflujo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='documentacion.documentasociadosdiagramasflujo')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DocumentImage_gestion_recursos_financieros', to='gestor_archivos.document_gestion_recursos_financieros')),
            ],
            options={
                'db_table': 'DocumentImage_gestion_recursos_financieros',
            },
            bases=('documentacion.documentasociadosdiagramasflujo',),
        ),
        migrations.CreateModel(
            name='DocumentImage_gestion_registro_calificado',
            fields=[
                ('documentasociadosdiagramasflujo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='documentacion.documentasociadosdiagramasflujo')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DocumentImage_gestion_registro_calificado', to='gestor_archivos.document_gestion_registro_calificado')),
            ],
            options={
                'db_table': 'DocumentImage_gestion_registro_calificado',
            },
            bases=('documentacion.documentasociadosdiagramasflujo',),
        ),
        migrations.CreateModel(
            name='DocumentImage_gestion_servicio_usuario',
            fields=[
                ('documentasociadosdiagramasflujo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='documentacion.documentasociadosdiagramasflujo')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DocumentImage_gestion_servicio_usuario', to='gestor_archivos.document_gestion_servicio_usuario')),
            ],
            options={
                'db_table': 'DocumentImage_gestion_servicio_usuario',
            },
            bases=('documentacion.documentasociadosdiagramasflujo',),
        ),
        migrations.CreateModel(
            name='DocumentImage_gestion_sistemas_comunicacion',
            fields=[
                ('documentasociadosdiagramasflujo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='documentacion.documentasociadosdiagramasflujo')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DocumentImage_gestion_sistemas_comunicacion', to='gestor_archivos.document_gestion_sistemas_comunicacion')),
            ],
            options={
                'db_table': 'DocumentImage_gestion_sistemas_comunicacion',
            },
            bases=('documentacion.documentasociadosdiagramasflujo',),
        ),
        migrations.CreateModel(
            name='DocumentImage_informacion_bibliografica',
            fields=[
                ('documentasociadosdiagramasflujo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='documentacion.documentasociadosdiagramasflujo')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DocumentImage_informacion_bibliografica', to='gestor_archivos.document_informacion_bibliografica')),
            ],
            options={
                'db_table': 'DocumentImage_informacion_bibliografica',
            },
            bases=('documentacion.documentasociadosdiagramasflujo',),
        ),
        migrations.CreateModel(
            name='DocumentImage_infraestructura_fisica',
            fields=[
                ('documentasociadosdiagramasflujo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='documentacion.documentasociadosdiagramasflujo')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DocumentImage_infraestructura_fisica', to='gestor_archivos.document_infraestructura_fisica')),
            ],
            options={
                'db_table': 'DocumentImage_infraestructura_fisica',
            },
            bases=('documentacion.documentasociadosdiagramasflujo',),
        ),
        migrations.CreateModel(
            name='DocumentImage_internacionalizacion',
            fields=[
                ('documentasociadosdiagramasflujo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='documentacion.documentasociadosdiagramasflujo')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DocumentImage_internacionalizacion', to='gestor_archivos.document_internacionalizacion')),
            ],
            options={
                'db_table': 'DocumentImage_internacionalizacion',
            },
            bases=('documentacion.documentasociadosdiagramasflujo',),
        ),
        migrations.CreateModel(
            name='DocumentImage_planeacion_estrategica_institucional',
            fields=[
                ('documentasociadosdiagramasflujo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='documentacion.documentasociadosdiagramasflujo')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DocumentImage_planeacion_estrategica_institucional', to='gestor_archivos.document_planeacion_estrategica_institucional')),
            ],
            options={
                'db_table': 'DocumentImage_planeacion_estrategica_institucional',
            },
            bases=('documentacion.documentasociadosdiagramasflujo',),
        ),
        migrations.CreateModel(
            name='DocumentImage_relacionamineto_egresados',
            fields=[
                ('documentasociadosdiagramasflujo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='documentacion.documentasociadosdiagramasflujo')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DocumentImage_relacionamineto_egresados', to='gestor_archivos.document_relacionamineto_egresados')),
            ],
            options={
                'db_table': 'DocumentImage_relacionamineto_egresados',
            },
            bases=('documentacion.documentasociadosdiagramasflujo',),
        ),
        migrations.CreateModel(
            name='DocumentDoAs_admisiones_registro_control_FoAs',
            fields=[
                ('documentformatosasociados_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='documentacion.documentformatosasociados')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DocumentDoAs_admisiones_registro_control_FoAs', to='gestor_archivos.document_admisiones_registro_control')),
            ],
            options={
                'db_table': 'DocumentDoAs_admisiones_registro_control_FoAs',
            },
            bases=('documentacion.documentformatosasociados',),
        ),
        migrations.CreateModel(
            name='DocumentDoAs_aseguramiento_calidad_academica_FoAs',
            fields=[
                ('documentformatosasociados_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='documentacion.documentformatosasociados')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DocumentDoAs_aseguramiento_calidad_academica_FoAs', to='gestor_archivos.document_aseguramiento_calidad_academica')),
            ],
            options={
                'db_table': 'DocumentDoAs_aseguramiento_calidad_academica_FoAs',
            },
            bases=('documentacion.documentformatosasociados',),
        ),
        migrations.CreateModel(
            name='DocumentDoAs_aseguramiento_calidad_procesos_FoAs',
            fields=[
                ('documentformatosasociados_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='documentacion.documentformatosasociados')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DocumentDoAs_aseguramiento_calidad_procesos_FoAs', to='gestor_archivos.document_aseguramiento_calidad_procesos')),
            ],
            options={
                'db_table': 'DocumentDoAs_aseguramiento_calidad_procesos_FoAs',
            },
            bases=('documentacion.documentformatosasociados',),
        ),
        migrations.CreateModel(
            name='DocumentDoAs_auditorias_FoAs',
            fields=[
                ('documentformatosasociados_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='documentacion.documentformatosasociados')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DocumentDoAs_auditorias_FoAs', to='gestor_archivos.document_auditorias')),
            ],
            options={
                'db_table': 'DocumentDoAs_auditorias_FoAs',
            },
            bases=('documentacion.documentformatosasociados',),
        ),
        migrations.CreateModel(
            name='DocumentDoAs_bienestar_institucional_FoAs',
            fields=[
                ('documentformatosasociados_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='documentacion.documentformatosasociados')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DocumentDoAs_bienestar_institucional_FoAs', to='gestor_archivos.document_bienestar_institucional')),
            ],
            options={
                'db_table': 'DocumentDoAs_bienestar_institucional_FoAs',
            },
            bases=('documentacion.documentformatosasociados',),
        ),
        migrations.CreateModel(
            name='DocumentDoAs_comunicacion_FoAs',
            fields=[
                ('documentformatosasociados_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='documentacion.documentformatosasociados')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DocumentDoAs_comunicacion_FoAs', to='gestor_archivos.document_comunicacion')),
            ],
            options={
                'db_table': 'DocumentDoAs_comunicacion_FoAs',
            },
            bases=('documentacion.documentformatosasociados',),
        ),
        migrations.CreateModel(
            name='DocumentDoAs_control_disciplinario_FoAs',
            fields=[
                ('documentformatosasociados_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='documentacion.documentformatosasociados')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DocumentDoAs_control_disciplinario_FoAs', to='gestor_archivos.document_control_disciplinario')),
            ],
            options={
                'db_table': 'DocumentDoAs_control_disciplinario_FoAs',
            },
            bases=('documentacion.documentformatosasociados',),
        ),
        migrations.CreateModel(
            name='DocumentDoAs_desarrollo_curricular_FoAs',
            fields=[
                ('documentformatosasociados_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='documentacion.documentformatosasociados')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DocumentDoAs_desarrollo_curricular_FoAs', to='gestor_archivos.document_desarrollo_curricular')),
            ],
            options={
                'db_table': 'DocumentDoAs_desarrollo_curricular_FoAs',
            },
            bases=('documentacion.documentformatosasociados',),
        ),
        migrations.CreateModel(
            name='DocumentDoAs_enseñanza_prendizaje_evaluacion_FoAs',
            fields=[
                ('documentformatosasociados_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='documentacion.documentformatosasociados')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DocumentDoAs_enseñanza_prendizaje_evaluacion_FoAs', to='gestor_archivos.document_enseñanza_prendizaje_evaluacion')),
            ],
            options={
                'db_table': 'DocumentDoAs_enseñanza_prendizaje_evaluacion_FoAs',
            },
            bases=('documentacion.documentformatosasociados',),
        ),
        migrations.CreateModel(
            name='DocumentDoAs_extension_proyeccion_FoAs',
            fields=[
                ('documentformatosasociados_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='documentacion.documentformatosasociados')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DocumentDoAs_extension_proyeccion_FoAs', to='gestor_archivos.document_extension_proyeccion')),
            ],
            options={
                'db_table': 'DocumentDoAs_extension_proyeccion_FoAs',
            },
            bases=('documentacion.documentformatosasociados',),
        ),
        migrations.CreateModel(
            name='DocumentDoAs_gestion_contractual_FoAs',
            fields=[
                ('documentformatosasociados_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='documentacion.documentformatosasociados')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DocumentDoAs_gestion_contractual_FoAs', to='gestor_archivos.document_gestion_contractual')),
            ],
            options={
                'db_table': 'DocumentDoAs_gestion_contractual_FoAs',
            },
            bases=('documentacion.documentformatosasociados',),
        ),
        migrations.CreateModel(
            name='DocumentDoAs_gestion_desarrollo_humano_FoAs',
            fields=[
                ('documentformatosasociados_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='documentacion.documentformatosasociados')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DocumentDoAs_gestion_desarrollo_humano_FoAs', to='gestor_archivos.document_gestion_desarrollo_humano')),
            ],
            options={
                'db_table': 'DocumentDoAs_gestion_desarrollo_humano_FoAs',
            },
            bases=('documentacion.documentformatosasociados',),
        ),
        migrations.CreateModel(
            name='DocumentDoAs_gestion_documental_FoAs',
            fields=[
                ('documentformatosasociados_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='documentacion.documentformatosasociados')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DocumentDoAs_gestion_documental_FoAs', to='gestor_archivos.document_gestion_documental')),
            ],
            options={
                'db_table': 'DocumentDoAs_gestion_documental_FoAs',
            },
            bases=('documentacion.documentformatosasociados',),
        ),
        migrations.CreateModel(
            name='DocumentDoAs_gestion_informacion_FoAs',
            fields=[
                ('documentformatosasociados_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='documentacion.documentformatosasociados')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DocumentDoAs_gestion_informacion_FoAs', to='gestor_archivos.document_gestion_informacion')),
            ],
            options={
                'db_table': 'DocumentDoAs_gestion_informacion_FoAs',
            },
            bases=('documentacion.documentformatosasociados',),
        ),
        migrations.CreateModel(
            name='DocumentDoAs_gestion_investigacion_FoAs',
            fields=[
                ('documentformatosasociados_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='documentacion.documentformatosasociados')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DocumentDoAs_gestion_investigacion_FoAs', to='gestor_archivos.document_gestion_investigacion')),
            ],
            options={
                'db_table': 'DocumentDoAs_gestion_investigacion_FoAs',
            },
            bases=('documentacion.documentformatosasociados',),
        ),
        migrations.CreateModel(
            name='DocumentDoAs_gestion_juridica_FoAs',
            fields=[
                ('documentformatosasociados_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='documentacion.documentformatosasociados')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DocumentDoAs_gestion_juridica_FoAs', to='gestor_archivos.document_gestion_juridica')),
            ],
            options={
                'db_table': 'DocumentDoAs_gestion_juridica_FoAs',
            },
            bases=('documentacion.documentformatosasociados',),
        ),
        migrations.CreateModel(
            name='DocumentDoAs_gestion_recursos_financieros_FoAs',
            fields=[
                ('documentformatosasociados_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='documentacion.documentformatosasociados')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DocumentDoAs_gestion_recursos_financieros_FoAs', to='gestor_archivos.document_gestion_recursos_financieros')),
            ],
            options={
                'db_table': 'DocumentDoAs_gestion_recursos_financieros_FoAs',
            },
            bases=('documentacion.documentformatosasociados',),
        ),
        migrations.CreateModel(
            name='DocumentDoAs_gestion_registro_calificado_FoAs',
            fields=[
                ('documentformatosasociados_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='documentacion.documentformatosasociados')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DocumentDoAs_gestion_registro_calificado_FoAs', to='gestor_archivos.document_gestion_registro_calificado')),
            ],
            options={
                'db_table': 'DocumentDoAs_gestion_registro_calificado_FoAs',
            },
            bases=('documentacion.documentformatosasociados',),
        ),
        migrations.CreateModel(
            name='DocumentDoAs_gestion_servicio_usuario_FoAs',
            fields=[
                ('documentformatosasociados_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='documentacion.documentformatosasociados')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DocumentDoAs_gestion_servicio_usuario_FoAs', to='gestor_archivos.document_gestion_servicio_usuario')),
            ],
            options={
                'db_table': 'DocumentDoAs_gestion_servicio_usuario_FoAs',
            },
            bases=('documentacion.documentformatosasociados',),
        ),
        migrations.CreateModel(
            name='DocumentDoAs_gestion_sistemas_comunicacion_FoAs',
            fields=[
                ('documentformatosasociados_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='documentacion.documentformatosasociados')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DocumentDoAs_gestion_sistemas_comunicacion_FoAs', to='gestor_archivos.document_gestion_sistemas_comunicacion')),
            ],
            options={
                'db_table': 'DocumentDoAs_gestion_sistemas_comunicacion_FoAs',
            },
            bases=('documentacion.documentformatosasociados',),
        ),
        migrations.CreateModel(
            name='DocumentDoAs_informacion_bibliografica_FoAs',
            fields=[
                ('documentformatosasociados_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='documentacion.documentformatosasociados')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DocumentDoAs_informacion_bibliografica_FoAs', to='gestor_archivos.document_informacion_bibliografica')),
            ],
            options={
                'db_table': 'DocumentDoAs_informacion_bibliografica_FoAs',
            },
            bases=('documentacion.documentformatosasociados',),
        ),
        migrations.CreateModel(
            name='DocumentDoAs_infraestructura_fisica_FoAs',
            fields=[
                ('documentformatosasociados_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='documentacion.documentformatosasociados')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DocumentDoAs_infraestructura_fisica_FoAs', to='gestor_archivos.document_infraestructura_fisica')),
            ],
            options={
                'db_table': 'DocumentDoAs_infraestructura_fisica_FoAs',
            },
            bases=('documentacion.documentformatosasociados',),
        ),
        migrations.CreateModel(
            name='DocumentDoAs_internacionalizacion_FoAs',
            fields=[
                ('documentformatosasociados_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='documentacion.documentformatosasociados')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DocumentDoAs_internacionalizacion_FoAs', to='gestor_archivos.document_internacionalizacion')),
            ],
            options={
                'db_table': 'DocumentDoAs_internacionalizacion_FoAs',
            },
            bases=('documentacion.documentformatosasociados',),
        ),
        migrations.CreateModel(
            name='DocumentDoAs_planeacion_estrategica_institucional_FoAs',
            fields=[
                ('documentformatosasociados_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='documentacion.documentformatosasociados')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DocumentDoAs_planeacion_estrategica_institucional_FoAs', to='gestor_archivos.document_planeacion_estrategica_institucional')),
            ],
            options={
                'db_table': 'DocumentDoAs_planeacion_estrategica_institucional_FoAs',
            },
            bases=('documentacion.documentformatosasociados',),
        ),
        migrations.CreateModel(
            name='DocumentDoAs_relacionamineto_egresados_FoAs',
            fields=[
                ('documentformatosasociados_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='documentacion.documentformatosasociados')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DocumentDoAs_relacionamineto_egresados_FoAs', to='gestor_archivos.document_relacionamineto_egresados')),
            ],
            options={
                'db_table': 'DocumentDoAs_relacionamineto_egresados_FoAs',
            },
            bases=('documentacion.documentformatosasociados',),
        ),
    ]
