# Generated by Django 5.1.4 on 2025-02-07 14:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentformatosasociados',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 7, 9, 33, 18)),
        ),
    ]
