# Generated by Django 5.1.4 on 2025-02-12 19:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentacion', '0005_alter_documentformatosasociados_fecha_creacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentformatosasociados',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 12, 14, 19, 44)),
        ),
    ]
