# Generated by Django 5.1.4 on 2025-02-12 19:33

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentacion', '0006_alter_documentformatosasociados_fecha_creacion'),
        ('gestor_archivos', '0005_document_gestion_cartera_indicadores_gestion_cartera'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentformatosasociados',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 12, 14, 33, 38)),
        ),
        migrations.CreateModel(
            name='DocumentDoAs_gestion_cartera_FoAs',
            fields=[
                ('documentformatosasociados_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='documentacion.documentformatosasociados')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DocumentDoAs_gestion_cartera_FoAs', to='gestor_archivos.document_gestion_cartera')),
            ],
            options={
                'db_table': 'DocumentDoAs_gestion_cartera_FoAs',
            },
            bases=('documentacion.documentformatosasociados',),
        ),
        migrations.CreateModel(
            name='DocumentImage_gestion_cartera',
            fields=[
                ('documentasociadosdiagramasflujo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='documentacion.documentasociadosdiagramasflujo')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DocumentImage_gestion_cartera', to='gestor_archivos.document_gestion_cartera')),
            ],
            options={
                'db_table': 'DocumentImage_gestion_cartera',
            },
            bases=('documentacion.documentasociadosdiagramasflujo',),
        ),
    ]
