# Generated by Django 5.1.4 on 2025-02-14 13:31

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentacion', '0007_alter_documentformatosasociados_fecha_creacion_and_more'),
        ('gestor_archivos', '0006_dipr_evaluacion_control_document_evaluacion_control_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentformatosasociados',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 14, 8, 31, 6)),
        ),
        migrations.CreateModel(
            name='DocumentDoAs_evaluacion_control_FoAs',
            fields=[
                ('documentformatosasociados_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='documentacion.documentformatosasociados')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DocumentDoAs_evaluacion_control_FoAs', to='gestor_archivos.document_evaluacion_control')),
            ],
            options={
                'db_table': 'DocumentDoAs_evaluacion_control_FoAs',
            },
            bases=('documentacion.documentformatosasociados',),
        ),
        migrations.CreateModel(
            name='DocumentImage_evaluacion_control',
            fields=[
                ('documentasociadosdiagramasflujo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='documentacion.documentasociadosdiagramasflujo')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DocumentImage_evaluacion_control', to='gestor_archivos.document_evaluacion_control')),
            ],
            options={
                'db_table': 'DocumentImage_evaluacion_control',
            },
            bases=('documentacion.documentasociadosdiagramasflujo',),
        ),
    ]
