# Generated by Django 5.1.4 on 2025-02-17 13:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentacion', '0008_alter_documentformatosasociados_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentformatosasociados',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 17, 8, 35, 19)),
        ),
    ]
