# Generated by Django 5.1.4 on 2025-02-17 16:17

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentacion', '0009_alter_documentformatosasociados_fecha_creacion'),
        ('gestor_archivos', '0007_dipr_gestion_integrada_document_gestion_integrada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentformatosasociados',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 17, 11, 17, 52)),
        ),
        migrations.CreateModel(
            name='DocumentDoAs_gestion_integrada_FoAs',
            fields=[
                ('documentformatosasociados_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='documentacion.documentformatosasociados')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DocumentDoAs_gestion_integrada_FoAs', to='gestor_archivos.document_gestion_integrada')),
            ],
            options={
                'db_table': 'DocumentDoAs_gestion_integrada_FoAs',
            },
            bases=('documentacion.documentformatosasociados',),
        ),
        migrations.CreateModel(
            name='DocumentImage_gestion_integrada',
            fields=[
                ('documentasociadosdiagramasflujo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='documentacion.documentasociadosdiagramasflujo')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DocumentImage_gestion_integrada', to='gestor_archivos.document_gestion_integrada')),
            ],
            options={
                'db_table': 'DocumentImage_gestion_integrada',
            },
            bases=('documentacion.documentasociadosdiagramasflujo',),
        ),
    ]
