# Generated by Django 5.1.2 on 2024-12-04 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Glosario',
            fields=[
                ('id_termino', models.AutoField(primary_key=True, serialize=False)),
                ('termino', models.CharField(max_length=150, verbose_name='termino')),
                ('definicion', models.TextField(max_length=2000, verbose_name='definicion')),
            ],
        ),
    ]
