# Generated by Django 5.1.4 on 2025-02-14 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapa_procesos', '0002_ec_gestion_cartera'),
    ]

    operations = [
        migrations.CreateModel(
            name='EC_evaluacion_control',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=100, unique=True)),
                ('content', models.TextField()),
            ],
        ),
    ]
