# Generated by Django 5.1.4 on 2025-02-17 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapa_procesos', '0004_videotutorial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EC_gestion_integrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=100, unique=True)),
                ('content', models.TextField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='videotutorial',
            options={'verbose_name': 'Tutorial', 'verbose_name_plural': 'Tutoriales'},
        ),
        migrations.AlterField(
            model_name='videotutorial',
            name='icon_class',
            field=models.CharField(max_length=50, verbose_name='Clase del ícono'),
        ),
        migrations.AlterField(
            model_name='videotutorial',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='videotutorial',
            name='video_id',
            field=models.CharField(max_length=20, verbose_name='ID del Video'),
        ),
    ]
