from django.urls import path
from mapa_procesos import views

urlpatterns = [
    path(
        "guardar-contenido/<str:model_name>/<str:folder_name>/<str:html_file_name>/",
        views.save_content_view,
        name="savecontent",
    ),
    path(
        "obtener-contenido/<str:model_name>/",
        views.get_content_view,
        name="obtener_contenido",
    ),
    path("mapa-procesos/", views.mapa_procesos, name="mapa-procesos"),
    path(
        "eliminar-tutorial/<int:tutorial_id>/",
        views.eliminar_tutorial,
        name="eliminar_tutorial",
    ),
    # URLS a HTML mapa de procesos primer paso
    # PROCESOS MISIONALES
    ###============
    path(
        "mapa-procesos/docencia-calidad/",
        views.docencia_calidad,
        name="docencia-calidad",
    ),
    # ==============
    ########################################################################
    path(
        "mapa-procesos/docencia-calidad/desarrollo-curricular/",
        views.desarrollo_curricular,
        name="desarrollo-curricular",
    ),
    ########################################################################
    path(
        "mapa-procesos/docencia-calidad/enseñanza-prendizaje-evaluacion/",
        views.enseñanza_prendizaje_evaluacion,
        name="enseñanza-prendizaje-evaluacion",
    ),
    ########################################################################
    ###============
    path(
        "mapa-procesos/investigacion-pertinente/",
        views.investigacion_pertinente,
        name="investigacion-pertinente",
    ),
    # ==============
    ########################################################################
    path(
        "mapa-procesos/investigacion-pertinente/gestion-investigacion/",
        views.gestion_investigacion,
        name="gestion-investigacion",
    ),
    ########################################################################
    ###============
    path(
        "mapa-procesos/proyeccion-social-impacto/",
        views.proyeccion_social_impacto,
        name="proyeccion-social-impacto",
    ),
    # ==============
    ########################################################################
    path(
        "mapa-procesos/proyeccion-social-impacto/extension-proyeccion/",
        views.extension_proyeccion,
        name="extension-proyeccion",
    ),
    ########################################################################
    path(
        "mapa-procesos/proyeccion-social-impacto/relacionamineto-egresados/",
        views.relacionamineto_egresados,
        name="relacionamineto-egresados",
    ),
    ########################################################################
    # PROCESOS DE APOYO
    ###============
    path(
        "mapa-procesos/gestion-infraestructura-fisica-tecnologica/",
        views.gestion_infraestructura_fisica_tecnologica,
        name="gestion-infraestructura-fisica-tecnologica",
    ),
    # ==============
    ########################################################################
    path(
        "mapa-procesos/gestion-infraestructura-fisica-tecnologica/gestion-sistemas-comunicacion/",
        views.gestion_sistemas_comunicacion,
        name="gestion-sistemas-comunicacion",
    ),
    ########################################################################
    path(
        "mapa-procesos/gestion-infraestructura-fisica-tecnologica/informacion-bibliografica/",
        views.informacion_bibliografica,
        name="informacion-bibliografica",
    ),
    ########################################################################
    path(
        "mapa-procesos/gestion-infraestructura-fisica-tecnologica/infraestructura-fisica/",
        views.infraestructura_fisica,
        name="infraestructura-fisica",
    ),
    ########################################################################
    ###============
    path(
        "mapa-procesos/gestion-administrativa-financiera/",
        views.gestion_administrativa_financiera,
        name="gestion-administrativa-financiera",
    ),
    # ==============
    ############################################################################
    path(
        "mapa-procesos/gestion-administrativa-financiera/gestion-cartera/",
        views.gestion_cartera,
        name="gestion-cartera",
    ),
    ############################################################################
    path(
        "mapa-procesos/gestion-administrativa-financiera/gestion-recursos-financieros/",
        views.gestion_recursos_financieros,
        name="gestion-recursos-financieros",
    ),
    ############################################################################
    path(
        "mapa-procesos/gestion-administrativa-financiera/gestion-documental/",
        views.gestion_documental,
        name="gestion-documental",
    ),
    ############################################################################
    ###============
    path(
        "mapa-procesos/gestion-mercadeo-admisiones/",
        views.gestion_mercadeo_admisiones,
        name="gestion-mercadeo-admisiones",
    ),
    # ==============
    ###########################################################################
    path(
        "mapa-procesos/gestion-mercadeo-admisiones/admisiones-registro-control/",
        views.admisiones_registro_control,
        name="admisiones-registro-control",
    ),
    ###########################################################################
    ##==================
    path(
        "mapa-procesos/gestion-juridica-contractual/",
        views.gestion_juridica_contractual,
        name="gestion-juridica-contractual",
    ),
    # ==============
    ############################################################################
    path(
        "mapa-procesos/gestion-juridica-contractual/gestion-juridica/",
        views.gestion_juridica,
        name="gestion-juridica",
    ),
    ############################################################################
    path(
        "mapa-procesos/gestion-juridica-contractual/gestion-contractual/",
        views.gestion_contractual,
        name="gestion-contractual",
    ),
    ############################################################################
    # DIRECCIONAMINETO ESTRATEGICO
    ###============
    path(
        "mapa-procesos/talento-humano-bienestar/",
        views.talento_humano_bienestar,
        name="talento-humano-bienestar",
    ),
    # ==============
    ############################################################################
    path(
        "mapa-procesos/talento-humano-bienestar/bienestar-institucional/",
        views.bienestar_institucional,
        name="bienestar-institucional",
    ),
    ############################################################################
    path(
        "mapa-procesos/talento-humano-bienestar/control-disciplinario/",
        views.control_disciplinario,
        name="control-disciplinario",
    ),
    ############################################################################
    path(
        "mapa-procesos/talento-humano-bienestar/gestion-desarrollo-humano/",
        views.gestion_desarrollo_humano,
        name="gestion-desarrollo-humano",
    ),
    ############################################################################
    ###============
    path(
        "mapa-procesos/calidad-integral/",
        views.calidad_integral,
        name="calidad-integral",
    ),
    # ==============
    ############################################################################
    path(
        "mapa-procesos/calidad-integral/aseguramiento-calidad-academica/",
        views.aseguramiento_calidad_academica,
        name="aseguramiento-calidad-academica",
    ),
    ############################################################################
    path(
        "mapa-procesos/calidad-integral/aseguramiento-calidad-procesos/",
        views.aseguramiento_calidad_procesos,
        name="aseguramiento-calidad-procesos",
    ),
    ############################################################################
    path(
        "mapa-procesos/calidad-integral/auditorias/",
        views.auditorias,
        name="auditorias",
    ),
    ############################################################################
    path(
        "mapa-procesos/calidad-integral/evaluacion-control/",
        views.evaluacion_control,
        name="evaluacion-control",
    ),
    ############################################################################
    path(
        "mapa-procesos/calidad-integral/gestion-integrada/",
        views.gestion_integrada,
        name="gestion-integrada",
    ),
    ############################################################################
    path(
        "mapa-procesos/calidad-integral/gestion-registro-calificado/",
        views.gestion_registro_calificado,
        name="gestion-registro-calificado",
    ),
    ############################################################################
    path(
        "mapa-procesos/calidad-integral/gestion-servicio-usuario/",
        views.gestion_servicio_usuario,
        name="gestion-servicio-usuario",
    ),
    ############################################################################
    ###============
    path(
        "mapa-procesos/relaciones-internacionales/",
        views.relaciones_internacionales,
        name="relaciones-internacionales",
    ),
    # ==============
    ############################################################################
    path(
        "mapa-procesos/relaciones-internacionales/comunicacion/",
        views.comunicacion,
        name="comunicacion",
    ),
    ############################################################################
    path(
        "mapa-procesos/relaciones-internacionales/internacionalizacion/",
        views.internacionalizacion,
        name="internacionalizacion",
    ),
    ############################################################################
    ###============
    path(
        "mapa-procesos/planeacion-estrategica/",
        views.planeacion_estrategica,
        name="planeacion-estrategica",
    ),
    # ==============
    ############################################################################
    path(
        "mapa-procesos/planeacion-estrategica/gestion-informacion/",
        views.gestion_informacion,
        name="gestion-informacion",
    ),
    ############################################################################
    path(
        "mapa-procesos/planeacion-estrategica/planeacion-estrategica-institucional/",
        views.planeacion_estrategica_institucional,
        name="planeacion-estrategica-institucional",
    ),
    ############################################################################
]
