# Generated by Django 5.1.2 on 2024-12-04 19:46

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiagramasProcedimientos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('nombre', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id_archivo', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=30, unique=True)),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('caracterizacion', models.CharField(blank=True, max_length=50, verbose_name='Caracterizacion')),
                ('file', models.FileField(max_length=200, upload_to='documents/', verbose_name='Archivo')),
                ('fecha_creacion', models.DateTimeField(default=datetime.datetime(2024, 12, 4, 14, 46, 56))),
            ],
            options={
                'unique_together': {('codigo',)},
            },
        ),
        migrations.CreateModel(
            name='DiPr_admisiones_registro_control',
            fields=[
                ('diagramasprocedimientos_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gestor_archivos.diagramasprocedimientos')),
            ],
            options={
                'db_table': 'DiPr_admisiones_registro_control',
            },
            bases=('gestor_archivos.diagramasprocedimientos',),
        ),
        migrations.CreateModel(
            name='DiPr_aseguramiento_calidad_academica',
            fields=[
                ('diagramasprocedimientos_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gestor_archivos.diagramasprocedimientos')),
            ],
            options={
                'db_table': 'DiPr_aseguramiento_calidad_academica',
            },
            bases=('gestor_archivos.diagramasprocedimientos',),
        ),
        migrations.CreateModel(
            name='DiPr_aseguramiento_calidad_procesos',
            fields=[
                ('diagramasprocedimientos_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gestor_archivos.diagramasprocedimientos')),
            ],
            options={
                'db_table': 'DiPr_aseguramiento_calidad_procesos',
            },
            bases=('gestor_archivos.diagramasprocedimientos',),
        ),
        migrations.CreateModel(
            name='DiPr_auditorias',
            fields=[
                ('diagramasprocedimientos_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gestor_archivos.diagramasprocedimientos')),
            ],
            options={
                'db_table': 'DiPr_auditorias',
            },
            bases=('gestor_archivos.diagramasprocedimientos',),
        ),
        migrations.CreateModel(
            name='DiPr_bienestar_institucional',
            fields=[
                ('diagramasprocedimientos_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gestor_archivos.diagramasprocedimientos')),
            ],
            options={
                'db_table': 'DiPr_bienestar_institucional',
            },
            bases=('gestor_archivos.diagramasprocedimientos',),
        ),
        migrations.CreateModel(
            name='DiPr_comunicacion',
            fields=[
                ('diagramasprocedimientos_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gestor_archivos.diagramasprocedimientos')),
            ],
            options={
                'db_table': 'DiPr_comunicacion',
            },
            bases=('gestor_archivos.diagramasprocedimientos',),
        ),
        migrations.CreateModel(
            name='DiPr_control_disciplinario',
            fields=[
                ('diagramasprocedimientos_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gestor_archivos.diagramasprocedimientos')),
            ],
            options={
                'db_table': 'DiPr_control_disciplinario',
            },
            bases=('gestor_archivos.diagramasprocedimientos',),
        ),
        migrations.CreateModel(
            name='DiPr_desarrollo_curricular',
            fields=[
                ('diagramasprocedimientos_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gestor_archivos.diagramasprocedimientos')),
            ],
            options={
                'db_table': 'DiPr_desarrollo_curricular',
            },
            bases=('gestor_archivos.diagramasprocedimientos',),
        ),
        migrations.CreateModel(
            name='DiPr_enseñanza_prendizaje_evaluacion',
            fields=[
                ('diagramasprocedimientos_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gestor_archivos.diagramasprocedimientos')),
            ],
            options={
                'db_table': 'DiPr_enseñanza_prendizaje_evaluacion',
            },
            bases=('gestor_archivos.diagramasprocedimientos',),
        ),
        migrations.CreateModel(
            name='DiPr_extension_proyeccion',
            fields=[
                ('diagramasprocedimientos_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gestor_archivos.diagramasprocedimientos')),
            ],
            options={
                'db_table': 'DiPr_extension_proyeccion',
            },
            bases=('gestor_archivos.diagramasprocedimientos',),
        ),
        migrations.CreateModel(
            name='DiPr_gestion_contractual',
            fields=[
                ('diagramasprocedimientos_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gestor_archivos.diagramasprocedimientos')),
            ],
            options={
                'db_table': 'DiPr_gestion_contractual',
            },
            bases=('gestor_archivos.diagramasprocedimientos',),
        ),
        migrations.CreateModel(
            name='DiPr_gestion_desarrollo_humano',
            fields=[
                ('diagramasprocedimientos_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gestor_archivos.diagramasprocedimientos')),
            ],
            options={
                'db_table': 'DiPr_gestion_desarrollo_humano',
            },
            bases=('gestor_archivos.diagramasprocedimientos',),
        ),
        migrations.CreateModel(
            name='DiPr_gestion_documental',
            fields=[
                ('diagramasprocedimientos_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gestor_archivos.diagramasprocedimientos')),
            ],
            options={
                'db_table': 'DiPr_gestion_documental',
            },
            bases=('gestor_archivos.diagramasprocedimientos',),
        ),
        migrations.CreateModel(
            name='DiPr_gestion_informacion',
            fields=[
                ('diagramasprocedimientos_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gestor_archivos.diagramasprocedimientos')),
            ],
            options={
                'db_table': 'DiPr_gestion_informacion',
            },
            bases=('gestor_archivos.diagramasprocedimientos',),
        ),
        migrations.CreateModel(
            name='DiPr_gestion_investigacion',
            fields=[
                ('diagramasprocedimientos_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gestor_archivos.diagramasprocedimientos')),
            ],
            options={
                'db_table': 'DiPr_gestion_investigacion',
            },
            bases=('gestor_archivos.diagramasprocedimientos',),
        ),
        migrations.CreateModel(
            name='DiPr_gestion_juridica',
            fields=[
                ('diagramasprocedimientos_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gestor_archivos.diagramasprocedimientos')),
            ],
            options={
                'db_table': 'DiPr_gestion_juridica',
            },
            bases=('gestor_archivos.diagramasprocedimientos',),
        ),
        migrations.CreateModel(
            name='DiPr_gestion_recursos_financieros',
            fields=[
                ('diagramasprocedimientos_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gestor_archivos.diagramasprocedimientos')),
            ],
            options={
                'db_table': 'DiPr_gestion_recursos_financieros',
            },
            bases=('gestor_archivos.diagramasprocedimientos',),
        ),
        migrations.CreateModel(
            name='DiPr_gestion_registro_calificado',
            fields=[
                ('diagramasprocedimientos_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gestor_archivos.diagramasprocedimientos')),
            ],
            options={
                'db_table': 'DiPr_gestion_registro_calificado',
            },
            bases=('gestor_archivos.diagramasprocedimientos',),
        ),
        migrations.CreateModel(
            name='DiPr_gestion_servicio_usuario',
            fields=[
                ('diagramasprocedimientos_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gestor_archivos.diagramasprocedimientos')),
            ],
            options={
                'db_table': 'DiPr_gestion_servicio_usuario',
            },
            bases=('gestor_archivos.diagramasprocedimientos',),
        ),
        migrations.CreateModel(
            name='DiPr_gestion_sistemas_comunicacion',
            fields=[
                ('diagramasprocedimientos_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gestor_archivos.diagramasprocedimientos')),
            ],
            options={
                'db_table': 'DiPr_gestion_sistemas_comunicacion',
            },
            bases=('gestor_archivos.diagramasprocedimientos',),
        ),
        migrations.CreateModel(
            name='DiPr_informacion_bibliografica',
            fields=[
                ('diagramasprocedimientos_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gestor_archivos.diagramasprocedimientos')),
            ],
            options={
                'db_table': 'DiPr_informacion_bibliografica',
            },
            bases=('gestor_archivos.diagramasprocedimientos',),
        ),
        migrations.CreateModel(
            name='DiPr_infraestructura_fisica',
            fields=[
                ('diagramasprocedimientos_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gestor_archivos.diagramasprocedimientos')),
            ],
            options={
                'db_table': 'DiPr_infraestructura_fisica',
            },
            bases=('gestor_archivos.diagramasprocedimientos',),
        ),
        migrations.CreateModel(
            name='DiPr_internacionalizacion',
            fields=[
                ('diagramasprocedimientos_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gestor_archivos.diagramasprocedimientos')),
            ],
            options={
                'db_table': 'DiPr_internacionalizacion',
            },
            bases=('gestor_archivos.diagramasprocedimientos',),
        ),
        migrations.CreateModel(
            name='DiPr_planeacion_estrategica_institucional',
            fields=[
                ('diagramasprocedimientos_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gestor_archivos.diagramasprocedimientos')),
            ],
            options={
                'db_table': 'DiPr_planeacion_estrategica_institucional',
            },
            bases=('gestor_archivos.diagramasprocedimientos',),
        ),
        migrations.CreateModel(
            name='DiPr_relacionamineto_egresados',
            fields=[
                ('diagramasprocedimientos_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gestor_archivos.diagramasprocedimientos')),
            ],
            options={
                'db_table': 'DiPr_relacionamineto_egresados',
            },
            bases=('gestor_archivos.diagramasprocedimientos',),
        ),
        migrations.CreateModel(
            name='Document_admisiones_registro_control',
            fields=[
                ('document_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gestor_archivos.document')),
            ],
            options={
                'db_table': 'document_admisiones_registro_control',
            },
            bases=('gestor_archivos.document',),
        ),
        migrations.CreateModel(
            name='Document_aseguramiento_calidad_academica',
            fields=[
                ('document_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gestor_archivos.document')),
            ],
            options={
                'db_table': 'document_aseguramiento_calidad_academica',
            },
            bases=('gestor_archivos.document',),
        ),
        migrations.CreateModel(
            name='Document_aseguramiento_calidad_procesos',
            fields=[
                ('document_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gestor_archivos.document')),
            ],
            options={
                'db_table': 'document_aseguramiento_calidad_procesos',
            },
            bases=('gestor_archivos.document',),
        ),
        migrations.CreateModel(
            name='Document_auditorias',
            fields=[
                ('document_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gestor_archivos.document')),
            ],
            options={
                'db_table': 'document_auditorias',
            },
            bases=('gestor_archivos.document',),
        ),
        migrations.CreateModel(
            name='Document_bienestar_institucional',
            fields=[
                ('document_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gestor_archivos.document')),
            ],
            options={
                'db_table': 'document_bienestar_institucional',
            },
            bases=('gestor_archivos.document',),
        ),
        migrations.CreateModel(
            name='Document_comunicacion',
            fields=[
                ('document_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gestor_archivos.document')),
            ],
            options={
                'db_table': 'document_comunicacion',
            },
            bases=('gestor_archivos.document',),
        ),
        migrations.CreateModel(
            name='Document_control_disciplinario',
            fields=[
                ('document_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gestor_archivos.document')),
            ],
            options={
                'db_table': 'document_control_disciplinario',
            },
            bases=('gestor_archivos.document',),
        ),
        migrations.CreateModel(
            name='Document_desarrollo_curricular',
            fields=[
                ('document_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gestor_archivos.document')),
            ],
            options={
                'db_table': 'document_desarrollo_curricular',
            },
            bases=('gestor_archivos.document',),
        ),
        migrations.CreateModel(
            name='Document_enseñanza_prendizaje_evaluacion',
            fields=[
                ('document_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gestor_archivos.document')),
            ],
            options={
                'db_table': 'document_enseñanza_prendizaje_evaluacion',
            },
            bases=('gestor_archivos.document',),
        ),
        migrations.CreateModel(
            name='Document_extension_proyeccion',
            fields=[
                ('document_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gestor_archivos.document')),
            ],
            options={
                'db_table': 'document_extension_proyeccion',
            },
            bases=('gestor_archivos.document',),
        ),
        migrations.CreateModel(
            name='Document_gestion_contractual',
            fields=[
                ('document_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gestor_archivos.document')),
            ],
            options={
                'db_table': 'document_gestion_contractual',
            },
            bases=('gestor_archivos.document',),
        ),
        migrations.CreateModel(
            name='Document_gestion_desarrollo_humano',
            fields=[
                ('document_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gestor_archivos.document')),
            ],
            options={
                'db_table': 'document_gestion_desarrollo_humano',
            },
            bases=('gestor_archivos.document',),
        ),
        migrations.CreateModel(
            name='Document_gestion_documental',
            fields=[
                ('document_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gestor_archivos.document')),
            ],
            options={
                'db_table': 'document_gestion_documental',
            },
            bases=('gestor_archivos.document',),
        ),
        migrations.CreateModel(
            name='Document_gestion_informacion',
            fields=[
                ('document_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gestor_archivos.document')),
            ],
            options={
                'db_table': 'document_gestion_informacion',
            },
            bases=('gestor_archivos.document',),
        ),
        migrations.CreateModel(
            name='Document_gestion_investigacion',
            fields=[
                ('document_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gestor_archivos.document')),
            ],
            options={
                'db_table': 'document_gestion_investigacion',
            },
            bases=('gestor_archivos.document',),
        ),
        migrations.CreateModel(
            name='Document_gestion_juridica',
            fields=[
                ('document_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gestor_archivos.document')),
            ],
            options={
                'db_table': 'document_gestion_juridica',
            },
            bases=('gestor_archivos.document',),
        ),
        migrations.CreateModel(
            name='Document_gestion_recursos_financieros',
            fields=[
                ('document_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gestor_archivos.document')),
            ],
            options={
                'db_table': 'document_gestion_recursos_financieros',
            },
            bases=('gestor_archivos.document',),
        ),
        migrations.CreateModel(
            name='Document_gestion_registro_calificado',
            fields=[
                ('document_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gestor_archivos.document')),
            ],
            options={
                'db_table': 'document_gestion_registro_calificado',
            },
            bases=('gestor_archivos.document',),
        ),
        migrations.CreateModel(
            name='Document_gestion_servicio_usuario',
            fields=[
                ('document_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gestor_archivos.document')),
            ],
            options={
                'db_table': 'document_gestion_servicio_usuario',
            },
            bases=('gestor_archivos.document',),
        ),
        migrations.CreateModel(
            name='Document_gestion_sistemas_comunicacion',
            fields=[
                ('document_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gestor_archivos.document')),
            ],
            options={
                'db_table': 'document_gestion_sistemas_comunicacion',
            },
            bases=('gestor_archivos.document',),
        ),
        migrations.CreateModel(
            name='Document_informacion_bibliografica',
            fields=[
                ('document_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gestor_archivos.document')),
            ],
            options={
                'db_table': 'document_informacion_bibliografica',
            },
            bases=('gestor_archivos.document',),
        ),
        migrations.CreateModel(
            name='Document_infraestructura_fisica',
            fields=[
                ('document_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gestor_archivos.document')),
            ],
            options={
                'db_table': 'document_infraestructura_fisica',
            },
            bases=('gestor_archivos.document',),
        ),
        migrations.CreateModel(
            name='Document_internacionalizacion',
            fields=[
                ('document_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gestor_archivos.document')),
            ],
            options={
                'db_table': 'document_internacionalizacion',
            },
            bases=('gestor_archivos.document',),
        ),
        migrations.CreateModel(
            name='Document_planeacion_estrategica_institucional',
            fields=[
                ('document_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gestor_archivos.document')),
            ],
            options={
                'db_table': 'document_planeacion_estrategica_institucional',
            },
            bases=('gestor_archivos.document',),
        ),
        migrations.CreateModel(
            name='Document_relacionamineto_egresados',
            fields=[
                ('document_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gestor_archivos.document')),
            ],
            options={
                'db_table': 'document_relacionamineto_egresados',
            },
            bases=('gestor_archivos.document',),
        ),
        migrations.CreateModel(
            name='Indicadores_admisiones_registro_control',
            fields=[
                ('document_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gestor_archivos.document')),
            ],
            options={
                'db_table': 'Indicadores_admisiones_registro_control',
            },
            bases=('gestor_archivos.document',),
        ),
        migrations.CreateModel(
            name='Indicadores_aseguramiento_calidad_academica',
            fields=[
                ('document_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gestor_archivos.document')),
            ],
            options={
                'db_table': 'Indicadores_aseguramiento_calidad_academica',
            },
            bases=('gestor_archivos.document',),
        ),
        migrations.CreateModel(
            name='Indicadores_aseguramiento_calidad_procesos',
            fields=[
                ('document_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gestor_archivos.document')),
            ],
            options={
                'db_table': 'Indicadores_aseguramiento_calidad_procesos',
            },
            bases=('gestor_archivos.document',),
        ),
        migrations.CreateModel(
            name='Indicadores_auditorias',
            fields=[
                ('document_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gestor_archivos.document')),
            ],
            options={
                'db_table': 'Indicadores_auditorias',
            },
            bases=('gestor_archivos.document',),
        ),
        migrations.CreateModel(
            name='Indicadores_bienestar_institucional',
            fields=[
                ('document_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gestor_archivos.document')),
            ],
            options={
                'db_table': 'Indicadores_bienestar_institucional',
            },
            bases=('gestor_archivos.document',),
        ),
        migrations.CreateModel(
            name='Indicadores_comunicacion',
            fields=[
                ('document_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gestor_archivos.document')),
            ],
            options={
                'db_table': 'Indicadores_comunicacion',
            },
            bases=('gestor_archivos.document',),
        ),
        migrations.CreateModel(
            name='Indicadores_control_disciplinario',
            fields=[
                ('document_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gestor_archivos.document')),
            ],
            options={
                'db_table': 'Indicadores_control_disciplinario',
            },
            bases=('gestor_archivos.document',),
        ),
        migrations.CreateModel(
            name='Indicadores_desarrollo_curricular',
            fields=[
                ('document_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gestor_archivos.document')),
            ],
            options={
                'db_table': 'Indicadores_desarrollo_curricular',
            },
            bases=('gestor_archivos.document',),
        ),
        migrations.CreateModel(
            name='Indicadores_enseñanza_prendizaje_evaluacion',
            fields=[
                ('document_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gestor_archivos.document')),
            ],
            options={
                'db_table': 'Indicadores_enseñanza_prendizaje_evaluacion',
            },
            bases=('gestor_archivos.document',),
        ),
        migrations.CreateModel(
            name='Indicadores_extension_proyeccion',
            fields=[
                ('document_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gestor_archivos.document')),
            ],
            options={
                'db_table': 'Indicadores_extension_proyeccion',
            },
            bases=('gestor_archivos.document',),
        ),
        migrations.CreateModel(
            name='Indicadores_gestion_contractual',
            fields=[
                ('document_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gestor_archivos.document')),
            ],
            options={
                'db_table': 'Indicadores_gestion_contractual',
            },
            bases=('gestor_archivos.document',),
        ),
        migrations.CreateModel(
            name='Indicadores_gestion_desarrollo_humano',
            fields=[
                ('document_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gestor_archivos.document')),
            ],
            options={
                'db_table': 'Indicadores_gestion_desarrollo_humano',
            },
            bases=('gestor_archivos.document',),
        ),
        migrations.CreateModel(
            name='Indicadores_gestion_documental',
            fields=[
                ('document_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gestor_archivos.document')),
            ],
            options={
                'db_table': 'Indicadores_gestion_documental',
            },
            bases=('gestor_archivos.document',),
        ),
        migrations.CreateModel(
            name='Indicadores_gestion_informacion',
            fields=[
                ('document_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gestor_archivos.document')),
            ],
            options={
                'db_table': 'Indicadores_gestion_informacion',
            },
            bases=('gestor_archivos.document',),
        ),
        migrations.CreateModel(
            name='Indicadores_gestion_investigacion',
            fields=[
                ('document_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gestor_archivos.document')),
            ],
            options={
                'db_table': 'Indicadores_gestion_investigacion',
            },
            bases=('gestor_archivos.document',),
        ),
        migrations.CreateModel(
            name='Indicadores_gestion_juridica',
            fields=[
                ('document_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gestor_archivos.document')),
            ],
            options={
                'db_table': 'Indicadores_gestion_juridica',
            },
            bases=('gestor_archivos.document',),
        ),
        migrations.CreateModel(
            name='Indicadores_gestion_recursos_financieros',
            fields=[
                ('document_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gestor_archivos.document')),
            ],
            options={
                'db_table': 'Indicadores_gestion_recursos_financieros',
            },
            bases=('gestor_archivos.document',),
        ),
        migrations.CreateModel(
            name='Indicadores_gestion_registro_calificado',
            fields=[
                ('document_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gestor_archivos.document')),
            ],
            options={
                'db_table': 'Indicadores_gestion_registro_calificado',
            },
            bases=('gestor_archivos.document',),
        ),
        migrations.CreateModel(
            name='Indicadores_gestion_servicio_usuario',
            fields=[
                ('document_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gestor_archivos.document')),
            ],
            options={
                'db_table': 'Indicadores_gestion_servicio_usuario',
            },
            bases=('gestor_archivos.document',),
        ),
        migrations.CreateModel(
            name='Indicadores_gestion_sistemas_comunicacion',
            fields=[
                ('document_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gestor_archivos.document')),
            ],
            options={
                'db_table': 'Indicadores_gestion_sistemas_comunicacion',
            },
            bases=('gestor_archivos.document',),
        ),
        migrations.CreateModel(
            name='Indicadores_informacion_bibliografica',
            fields=[
                ('document_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gestor_archivos.document')),
            ],
            options={
                'db_table': 'Indicadores_informacion_bibliografica',
            },
            bases=('gestor_archivos.document',),
        ),
        migrations.CreateModel(
            name='Indicadores_infraestructura_fisica',
            fields=[
                ('document_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gestor_archivos.document')),
            ],
            options={
                'db_table': 'Indicadores_infraestructura_fisica',
            },
            bases=('gestor_archivos.document',),
        ),
        migrations.CreateModel(
            name='Indicadores_internacionalizacion',
            fields=[
                ('document_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gestor_archivos.document')),
            ],
            options={
                'db_table': 'Indicadores_internacionalizacion',
            },
            bases=('gestor_archivos.document',),
        ),
        migrations.CreateModel(
            name='Indicadores_planeacion_estrategica_institucional',
            fields=[
                ('document_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gestor_archivos.document')),
            ],
            options={
                'db_table': 'Indicadores_planeacion_estrategica_institucional',
            },
            bases=('gestor_archivos.document',),
        ),
        migrations.CreateModel(
            name='Indicadores_relacionamineto_egresados',
            fields=[
                ('document_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gestor_archivos.document')),
            ],
            options={
                'db_table': 'Indicadores_relacionamineto_egresados',
            },
            bases=('gestor_archivos.document',),
        ),
    ]
