# Generated by Django 5.1.4 on 2025-02-12 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_archivos', '0004_dipr_gestion_cartera'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document_gestion_cartera',
            fields=[
                ('document_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gestor_archivos.document')),
            ],
            options={
                'db_table': 'document_gestion_cartera',
            },
            bases=('gestor_archivos.document',),
        ),
        migrations.CreateModel(
            name='Indicadores_gestion_cartera',
            fields=[
                ('document_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gestor_archivos.document')),
            ],
            options={
                'db_table': 'Indicadores_gestion_cartera',
            },
            bases=('gestor_archivos.document',),
        ),
    ]
