# Generated by Django 5.1.4 on 2025-02-14 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_archivos', '0005_document_gestion_cartera_indicadores_gestion_cartera'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiPr_evaluacion_control',
            fields=[
                ('diagramasprocedimientos_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gestor_archivos.diagramasprocedimientos')),
            ],
            options={
                'db_table': 'DiPr_evaluacion_control',
            },
            bases=('gestor_archivos.diagramasprocedimientos',),
        ),
        migrations.CreateModel(
            name='Document_evaluacion_control',
            fields=[
                ('document_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gestor_archivos.document')),
            ],
            options={
                'db_table': 'document_evaluacion_control',
            },
            bases=('gestor_archivos.document',),
        ),
        migrations.CreateModel(
            name='Indicadores_evaluacion_control',
            fields=[
                ('document_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gestor_archivos.document')),
            ],
            options={
                'db_table': 'Indicadores_evaluacion_control',
            },
            bases=('gestor_archivos.document',),
        ),
    ]
